Fix build errors after rebasing on upstream
Synced my fork with upstream QMK and started getting build errors.

```
quantum/rgblight/rgblight.h:21:0: error: "RGBLIGHT_LED_COUNT" redefined [-Werror]
 #    define RGBLIGHT_LED_COUNT RGBLED_NUM
```

Looked at the config.h file in keyboards/redox/rev1 and saw those
variables aren't being defined anymore. Looks like that kind of
configuration is happening in a JSON file instead, according to some of
the commits in that folder.

Anyways, remove those configuration settings in the header file, and now
my keymap compiles successfully.